INSERT INTO `crypto_monney`.`cryptomoney`(`id`,`miniIdMonnaieCrypto`,`nomMonnaieCrypto`,`price`) VALUES (1,'ADA', 'Cardano','125');
INSERT INTO `crypto_monney`.`cryptomoney`(`id`,`miniIdMonnaieCrypto`,`nomMonnaieCrypto`,`price`) VALUES (2,'BCH', 'Bitcoin Cash','125');
INSERT INTO `crypto_monney`.`cryptomoney`(`id`,`miniIdMonnaieCrypto`,`nomMonnaieCrypto`,`price`) VALUES (3,'BTC', 'Bitcoin','125');
INSERT INTO `crypto_monney`.`cryptomoney`(`id`,`miniIdMonnaieCrypto`,`nomMonnaieCrypto`,`price`) VALUES (4,'BTM', 'Bytom','125');
INSERT INTO `crypto_monney`.`cryptomoney`(`id`,`miniIdMonnaieCrypto`,`nomMonnaieCrypto`,`price`) VALUES (5,'DASH', 'DASH','125');
INSERT INTO `crypto_monney`.`cryptomoney`(`id`,`miniIdMonnaieCrypto`,`nomMonnaieCrypto`,`price`) VALUES (6,'DGB', 'DigiByte','125');
INSERT INTO `crypto_monney`.`cryptomoney`(`id`,`miniIdMonnaieCrypto`,`nomMonnaieCrypto`,`price`) VALUES (7,'EOS', 'EOS','125');
INSERT INTO `crypto_monney`.`cryptomoney`(`id`,`miniIdMonnaieCrypto`,`nomMonnaieCrypto`,`price`) VALUES (8,'ETH', 'Ethereum','125');
INSERT INTO `crypto_monney`.`cryptomoney`(`id`,`miniIdMonnaieCrypto`,`nomMonnaieCrypto`,`price`) VALUES (9,'HSR', 'Hshare','125');
INSERT INTO `crypto_monney`.`cryptomoney`(`id`,`miniIdMonnaieCrypto`,`nomMonnaieCrypto`,`price`) VALUES (10,'ICX', 'ICON','125');
INSERT INTO `crypto_monney`.`cryptomoney`(`id`,`miniIdMonnaieCrypto`,`nomMonnaieCrypto`,`price`) VALUES (11,'LTC', 'LiteCoin','125');
INSERT INTO `crypto_monney`.`cryptomoney`(`id`,`miniIdMonnaieCrypto`,`nomMonnaieCrypto`,`price`) VALUES (12,'MCO', 'MCO','125');
INSERT INTO `crypto_monney`.`cryptomoney`(`id`,`miniIdMonnaieCrypto`,`nomMonnaieCrypto`,`price`) VALUES (13,'NEO', 'NEO','125');